### ISSUE TITLE
Wrong Parameter Name with Default Sort

### ISSUE THREAD

**Issue by tkalmar** [springdoc/springdoc-openapi#1010]
**Describe the bug**
When a controller `Pageable` method parameter is annotated with `@PageableDefault` and a sort Parameter is given in the annotation the parameter name for the sort is not sort. Instead it is the value of the sort Parameter.
The cause is: 
https://github.com/springdoc/springdoc-openapi/blob/c567f677445a68fe11daa508567ca743c7916486/springdoc-openapi-data-rest/src/main/java/org/springdoc/data/rest/customisers/DataRestDelegatingMethodParameterCustomizer.java#L409-L410

**To Reproduce**
Following Controller Method triggers the bug
```java
  @Operation(description = "SomeDescription")
  @GetMapping("/")
  public String getPatientList(@PageableDefault(size = 100, sort = { "someField" }, direction = Sort.Direction.ASC)
                                            @ParameterObject
                                            Pageable pageable){
return "bla";
}
```
leads to:
```javascript
{
            "name": "someField",
            "in": "query",
            "description": "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.",
            "required": false,
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
```

**Expected behavior**
the field name should stay `sort` the default value should be `someField,asc` (notice value + sort direction)
The only time the field name should be changed, is when annotated with `@Qualifier` which seems also not supported.

**Screenshots**

**Additional context**

**Comment by bnasslahsen** [comment]
@tkalmar, 

 The wrong parameter naming is now fixed.

Note that `@Qualifier`is only for adding a prefix to properties naming.
For changing properties names, you have 2 additional ways through configuration properties available on `SpringDataWebProperties` and `RepositoryRestConfiguration`.

 For the default value of the `sort` Parameter, it actually depends on the default value of the annoatation @ArraySchema which is used internally by springdoc-openapi to map the value. 

 This is unfortunate, because the `@ArraySchema` annotation does not contain the default value, even this annotation exists on the `@Schema` level.

 This can be added through `OpenApiCustomiser`, but it seems too much.
 If you need it out of the box, in springdoc-openapi, the straight forward way is to submit an enhancement request to the [swagger-core project](https://github.com/swagger-api/swagger-core) to add the defaultValue on @ArraySchema annotation.

**Comment by tkalmar** [comment]
@bnasslahsen Isn't `@ArraySchmema` arrayschema attribute used to define defaults for the array schema?

**Comment by bnasslahsen** [comment]
it is indeed...
