### ISSUE TITLE
GroupedOpenApi returns 404 for /v3/api-docs/groupName

### ISSUE THREAD

**Issue by Fredrik5** [springdoc/springdoc-openapi#1016]
Hey there, 

i am using kind of default configuration as I saw that in demos project. 

My only dependecy is 

`<dependency>
<groupId>org.springdoc</groupId>
<artifactId>springdoc-openapi-ui</artifactId>
<version>1.5.2</version>
</dependency>`

Configurations

	@Bean
	public GroupedOpenApi vehicle() {
		String paths[] = { "/**/vehicle/**" };
		return GroupedOpenApi.builder().setGroup("codetable").pathsToMatch(paths)
				.build();
	}

	@Bean
	public GroupedOpenApi codetable() {
		String paths[] = { "/**/codetable/**" };
		return GroupedOpenApi.builder().setGroup("codetable").pathsToMatch(paths)
				.build();
	}

applicaiton.properties
`springdoc.api-docs.groups.enabled=true`

_And that's it. I have couple scenarions which works._

http://localhost:10015/restapi-vehicle/services/rest/v3/api-docs **- works, returns all paths and other info**

http://localhost:10015/restapi-vehicle/services/rest/swagger-ui/index.html?configUrl=/restapi-vehicle/services/rest/v3/api-docs/swagger-config **- works**

http://localhost:10015/restapi-vehicle/services/rest/v3/api-docs/swagger-config **- works, returning urls for my GroupedOpenApi beans**

But the groupName EPs returns 404
http://localhost:10015/restapi-vehicle/services/rest/v3/api-docs/vehicle
http://localhost:10015/restapi-vehicle/services/rest/v3/api-docs/codetable

![image](https://user-images.githubusercontent.com/50204564/104596561-6b389f00-5674-11eb-86ef-5f0400231355.png)

Is the 1.5.2 release has a bug for groupName configs or am I missing something in the configurations? 

Thank for your time

**Comment by bnasslahsen** [comment]
@Fredrik5, 

 I don't understand how your code, could even compile because `setGroup` which doesn't exist in 1.5.2.

 You have available [code demos for mvc](https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-spring-boot-2-webmvc), and [code demos for webflux](https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-spring-boot-2-webflux)

 These [demos](https://springdoc.org/#demos) are deployed through CI/CD without any issues.
