### ISSUE TITLE
Schema with @JsonUnwrapped does not include required properties

### ISSUE THREAD

**Issue by tobi6112** [springdoc/springdoc-openapi#1060]
*Edit: Tell me If i'm wrong but it seems really to be a bug of `swagger-core`. I have resolved it locally and will create an PR on their side. 

**Describe the bug**
When a Type is annotated with `@JsonUnwrapped` and the unwrapped class does have required properties they won't be mapped to the unwrapping Schema. 
At first I thought this might be a bug of swagger-core but since Springfox does handle that correctly I think it belongs here?

**To Reproduce**
As usual I've updated my repository: https://github.com/tobi6112/springdoc-issue-demo

For reference here is it also as code example:

**application.properties**
  ```properties
springdoc.remove-broken-reference-definitions=false
  ```
**Bar**
```java
public class Bar <T> {
  private T content;

  protected Bar() {
    this.content = null;
  }

  public static <T> Bar<T> of(T content) {
    return of(content);
  }

  @Nullable
  @JsonUnwrapped
  public T getContent() {
    return this.content;
  }
}
```
**Foo**
```java
@Data
@AllArgsConstructor
public class Foo {
  @NotNull String foo;
  String secondProperty;
}
```

**FooController**
```java
@RestController
public class FooController {

  @GetMapping(value = "foos")
  public ResponseEntity<Bar<Foo>> getFoo() {
    var foo = new Foo("test");
    return ResponseEntity.ok(Bar.of(foo));
  }
}
```

**Expected behavior**
```json
"BarFoo": {
  "required": [
    "foo"
  ],
  "type": "object",
  "properties": {
    "foo": {
      "type": "string"
    },
    "secondProperty": {
      "type": "string"
    }
  }
}
```

**Actual behavior**
```json
"BarFoo": {
  "type": "object",
  "properties": {
    "foo": {
      "type": "string"
    },
    "secondProperty": {
      "type": "string"
    }
  }
}
```

**Additional Context**
I personally have this problem with [`org.springframework.hateoas.EntityModel`](https://docs.spring.io/spring-hateoas/docs/current/api/org/springframework/hateoas/EntityModel.html) since it Unwraps the content.

**Comment by toucheqt** [comment]
Can confirm this. The generator currently contains a bug that does not copy required properties when using @JsonUnwrapped.

In addition, I would like to ask if it is possible to make the ModelResolver#handleUnwrapped method protected, so it can be overriden in custom model resolver.

Currently there is an issue with using custom JacksonAnnotationIntrospector that alters the properties, because the current implementaion of handleUnwrapped ignores custom introspectors. For instance, if our custom introspector capitalize the property when the @JsonUnwrapped(prefix = "prefix"), the property in the API is not capitalized.

**Comment by bnasslahsen** [comment]
@toucheqt and @tobi6112, 

 Please not this is related to an existing issue with the swagger-core generator, which is already logged in swagger-core [project](https://github.com/swagger-api/swagger-core/issues/3683).

 You can try to propose a PR on the swagger-core about it.
Once the fix is available, we will ship the last version in springdoc-openapi.
