### ISSUE TITLE
Add support for object as request parameter container

### ISSUE THREAD

**Issue by joaodias14** [springdoc/springdoc-openapi#120]
Spring supports that an object is used to define query parameters as shown below:

**Controller**
```
@RestController
public class MealPartiesAdminController {
    @GetMapping(value = "/parties/{id}")
    public MealParty getMealParty(@PathVariable("id") long mealPartyId, MealPartiesQuery query){
        return this.mealPartyAdminService.getMealParty(mealPartyId, query);
    }
}
```

**Model**
```
public class MealPartiesQuery {
    private String name;
    private int membersCount;
}
```

Both `name` and `membersCount` are now endpoint query parameters. However, the generated swagger information only shows the query as an object. I've also added `@ModelAttribute` to `query` parameter in the controller but it still shows it as an object.
Am I missing something or there is no support for this currently?

**Comment by springdoc** [comment]
Hi, 

 Because you are using GET HTTP method, to pass an object. The second argument will be shown as an object.  (It should be sent as json object)

 We generate the OpenAPI description, and then we mainly rely on the official swagger jars (annotations/models/ui) .
 This is the behaviour of swagger-ui. And there is a related enhancement on swagger-ui that we follow. This isn't yet resolved:

- swagger-api/swagger-ui#4581

**Comment by joaodias14** [comment]
Hi,

Many thanks for the quick response. 
I am almost sure this worked with springfox, so maybe it was performing additional annotations processing. We will wait for that improve on swagger-ui.

**Comment by SimpleCookie** [comment]
It does work with SpringFox. I just switched from SpringFox to SpringDoc OpenApi and I'm now encountering this issue, thinking how I should resolve it. I have my code something like this
`public class Foo {
    private final String val;    public Foo(String val) {
        this.val = val;
    }    @Override
    public String toString() {
        return this.val;
    }
}@GetMapping(value = "/something", produces = MediaType.APPLICATION_JSON_VALUE)
public int func(@Parameter(name = "foo") @RequestParam Optional<Foo> foo) {
    return 7;
}`

Ideally I'd like to keep it this way and fix it by annotations instead of changing the type to a String.

**Comment by gerasimovv88** [comment]
Hi!
I switched from SpringFox to SpringDoc too and have the same issue.

I have a request model ("multipart/form-data", for example) with nested object here.
```
@ApiOperation(...)
@PostMapping(value = ..., consumes = MediaType.MULTIPART_FORM_DATA_VALUE) 
public void save(TestModel testModel) {....}
```

**TestModel** is:
```
@ApiModel(description = "Some test model description")
public class TestModel {
       @ApiModelProperty(value = "Some name description")
	private String name;

       @ApiModelProperty(value = "Some details description")
	private Details details;
}
```
And **InnerObject** is: 
```
@ApiModel(description = "Some details description")
public class Details {
	@ApiModelProperty(value = "Some title description")
	private String title;

	@ApiModelProperty(value = "Some age description")
	private int age;

	@ApiModelProperty(value = "Some additional info description")
	private String additionalInfo;
}
```

In Swagger UI I see this @ApiOperation. Model expanded as a **separated** parameters like this:

- name
- details.title
- details.age
- details.additionalInfo
The request in curl was generated **correctly** like this:

````
curl -X POST "..." -H "accept: */*" -H "Content-Type: multipart/form-data" -F "name=Ivan"
-F "details.title=test1" -F "details.age=18" -F "details.additionalInfo=info"
````

Now in SpringDoc I have the same request with same model. 
@ApiOperation --> @Operation too.
**TestModel** is:
```
@Schema(description = "Some test model description")
public class TestModel {
       @Schema(description = "Some name description")
	private String name;

       @Schema(description = "Some details description")
	private Details details;
}
```
And **InnerObject** is: 
```
@Schema(description = "Some details description")
public class Details {
	@Schema(description = "Some title description")
	private String title;

	@Schema(description = "Some age description")
	private int age;

	@Schema(description = "Some additional info description")
	private String additionalInfo;
}
```
In Swagger UI I see this @Operation. Model doesn't expanded as a separated parameters. And I see details field as a object instead of separated inner parameters. (see example above).

- name
- details
Of course, if i click "Try in out", details expanded like this:
````
{
  "title": "string",
  "age": 0,
  "additionalInfo": "string"
}
````
The request in curl was generated **incorrectly** like this:
curl -X POST "..." -H "accept: */*" -H "Content-Type: multipart/form-data" -F "type=" -F "details={"title": "string", "age": 0,"additionalInfo": "string"}" -F "name=Ivan"

How I can get expected behaviour as described above? 
I like SpringDoc, but I was embarrassed)
Thank you!

**Comment by gerasimovv88** [comment]
I have just looked a https://github.com/springdoc/springdoc-openapi/pull/505
I'm not sure, but it can help, isn't it?

**Comment by zarebski-m** [comment]
It definitely can help, but at the moment it does not support nested parameter objects.

**Comment by annassi-code** [comment]
please, is it resolved ?

**Comment by bnasslahsen** [comment]
see https://github.com/springdoc/springdoc-openapi/pull/605
