### ISSUE TITLE
Spring boot actuator endpoint parameters not shown when endpoint not prefixed by /actuator/

### ISSUE THREAD

**Issue by Crystark** [springdoc/springdoc-openapi#1234]
I'm following up on #775
A [fix](https://github.com/springdoc/springdoc-openapi/commit/b57116fdb721fdd83252c3be3ca072d1f2bbb16f) was added but this fix only handles actuator endpoints when they start by `/actuator/`.

We do not use the /actuator prefix as we have the following configuration:
```
management.endpoints.web.base-path: /
```
As such the fix doesn't work for us.

Moreover, I can't just use the workaround explained in the #775 issue because I get the following error if I do so:
```
The bean 'actuatorOpenApiCustomiser', defined in class path resource [org/springdoc/core/SpringDocConfiguration$SpringDocActuatorConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [My.class] and overriding is disabled.
```

**Comment by bnasslahsen** [comment]
@Crystark, 
 
Please before raising any issue, make sure you reference the last stable version. (we are today in `v1.5.10`)
The fix you are referencing is obsolete...

You have the guidance [here](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc) for using GitHub Issues: 
`If you are starting using springdoc-openapi, we advise you to use the last available release.`

The `ActuatorOpenApiCustomizer` is based on the actuator prefix `management.endpoints.web.base-path` since version [v1.5.1 since 2020-12-07](https://github.com/springdoc/springdoc-openapi/blob/master/CHANGELOG.md). 

This ticket will be closed and can be reopened if believe you are still facing an issue. At this moment, make sure you add all the information listed in the [guidance](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc) for opening GitHub Issues.
