### ISSUE TITLE
Generate API from yml directly

### ISSUE THREAD

**Issue by sonOfRa** [springdoc/springdoc-openapi#131]
I think this is related to #45 .

What I'd like to do is, instead of generating the .yml file on the fly from annotations, is use a pre-defined .yml file in order to generate the documentation: This way swagger-ui automatically runs in the same host:port combination as the spring boot application itself, and one doesn't have to bend over backwards in order to make the browser shut up about CORS violations: If I run swagger-ui standalone, and obviously on a different port than the spring-boot application itself, I'll have to configure spring-boot to allow Cross-Origin Requests from whatever port swagger-ui is running on.

Is this supported by springdoc?

**Comment by springdoc** [comment]
Hi, 

 If you want to use swagger-ui in standalone mode with a generated yaml file as input.
 You can use the following plugin, to generate your swagger and serve it from swagger-ui directly: https://github.com/springdoc/springdoc-openapi-maven-plugin.git

 Otherwise, you will have to  allow CORS on your spring-boot application.
