### ISSUE TITLE
Spring Native Support

### ISSUE THREAD

**Issue by AlexanderNZ** [springdoc/springdoc-openapi#1437]
**Describe the bug**
Spring Native builds fail when springdoc-openapi dependencies are located in `build.gradle`

**To Reproduce**
- Spring Boot 2.6.2, Gradle 7.3.2, Java 17
- org.springdoc:springdoc-openapi UI, hateoas, security, native all at 1.6.3
- Expected: `./gradlew bootBuildImage` finishes successfully, Actual - build error, see readme of attached project
- Issue is reproducible by cloning and following readme steps of sample repository: https://github.com/AlexanderNZ/springdoc-native-sample

**Expected behavior**
- Build finishes successfuly

**Additional context**
Sample reproduction repository: https://github.com/AlexanderNZ/springdoc-native-sample

**Comment by AlexanderNZ** [comment]
This template feels cold and informal but I understand why you have it. I've really enjoyed using springdoc!
I recently wanted to add native compilation to my project but it looks like even with the latest versions of Spring Boot, Native and Springdoc, there is an issue with native compilation.

**Comment by bnasslahsen** [comment]
@AlexanderNZ, 

Note the issue you are reporting only happens when you use: `spring-hateoas`.
Otherwise, commenting the dependency will make the build pass:  

```groovy
implementation 'org.springdoc:springdoc-openapi-hateoas:1.6.3'
```

If i assume you want to use `spring-hateoas` with `spring-native`, you will need to wait for [this spring-native issue](https://github.com/spring-projects-experimental/spring-native/issues/969) to be resolved or contribute on it's resolution.

It would be great if you can update your empty project with the following [PR](https://github.com/AlexanderNZ/springdoc-native-sample/pull/1): It provides a simple way to reproduce the issue for the `spring-native` team:
```java
@RestController
class HelloController {

	@GetMapping("/persons")
	public String persons() {
		return null;
	}

}
```

Once done, i advice you to update [this issue](https://github.com/spring-projects-experimental/spring-native/issues/969) with the link to your minimal project.

You can use spring-native GITHUB to track this issue and if you face other issue, feel free to update this ticket.
