### ISSUE TITLE
No converter for [class org.springframework.security.oauth2.common.DefaultOAuth2AccessToken] with preset Content-Type 'application/json;charset=UTF-8'

### ISSUE THREAD

**Issue by alexeil** [springdoc/springdoc-openapi#157]
I'm currently using Spring Boot 2.2.0 with Spring Security and JWT Token.

I added springdoc-openapi-ui 1.2.6 to the project and I can successfully access https://localhost:8080/swagger-ui/index.html.

Though, since I added the dependency the "/oauth/token" is broken. I receive this error : No converter for [class org.springframework.security.oauth2.common.DefaultOAuth2AccessToken] with preset Content-Type 'application/json;charset=UTF-8'.

This doesn't make any sense to me and I couldn't figure out weither there was a conflict somewhere.

Thank you

**Comment by springdoc** [comment]
Hi, 

 springdoc-openapi-ui supports spring-boot v2.2.0. 
 There are no known issues  about the compatibility with spring-security.

 It's difficult to answer your issue without a clear description of your context.
 
 You can attach or add the link to a sample project in order to reproduce your issue.
 We will reopen the issue when you provide the necessary elements to investigate.
