### ISSUE TITLE
Any plan to make the POJO parameter binding same as SpringMVC ?

### ISSUE THREAD

**Issue by JaynLau** [springdoc/springdoc-openapi#162]
Now, the POJO object without @RequestBody is binded to request body, but in SpringMVC, the properties of the POJO object without @RequestBody are binded to request parameters.

Is there any plan to change this same as SpringMVC ?

**Comment by springdoc** [comment]
Hi, 

This behaviour depends on the HTTP method you are using.
For example, if you use `@GetMapping` the POJO object without `@Requestbody` will be bound to request parameters.
If you use `@PostMapping` the POJO object without `@Requestbody` will be bound to request body in order to be compliant with what the spring-rest-mvc API is expecting.
 
 You can add sample Java Code with the expected and the actual OpenAPI description (Json/yml) , if you think there any potential issue.

**Comment by quaff** [comment]
> If you use @PostMapping the POJO object without @RequestBody will be bound to request body in order to be compliant with what the spring-rest-mvc API is expecting.

@bnasslahsen I'm afraid you are wrong, POJO without `@RequestBody` will always be bound from request parameters.
According to that, `@ParameterObject` introduced by #505 is redundant since all unannotated POJO should be treated as parameter object, as springfox does.
