### ISSUE TITLE
Support https

### ISSUE THREAD

**Issue by canchanchara** [springdoc/springdoc-openapi#171]
I'm using springdoc with spring boot in a docker container.
The container is starting under port 8080.
The docker host is running an apache webserver with an reverse proxy to my docker image.

So I can browse to:

> https://mywebsite.net/swagger-ui/index.html?url=/v3/api-docs

It shows the correct swagger UI.

The servers shows:

> http://mywebsite.net - generated Server url.

It is intelligent, it shows the public domain with the right port, not the 'inside docker ip/port"

Can you fix it, that it is using **https** instead of **http** if I browse via https to the swagger documentation?

Otherwise the try it feature is not working. It is blocked to use a http rest api in a https website.

**Comment by springdoc** [comment]
Hi, 
 
 **https** is already supported.You have to review your spring-boot app / reverse proxy configuration.

 In general, you should set the following headers in your reverse proxy configuration:

```properties
RequestHeader set X-Forwarded-Prefix "/custom-path"
RequestHeader set X-Forwarded-Proto https
RequestHeader set X-Forwarded-Port 443
```

Then, in your spring-boot application make sure your application handles this header: X-Forwarded-For. There are two ways to achieve this:

- Since spring-boot 2.2, there is a new property to handle reverse proxy headers:

```properties
server.forward-headers-strategy=framework
```
 

- Or you you can add the following Bean to your application:

```java
@Bean
ForwardedHeaderFilter forwardedHeaderFilter() {
   return new ForwardedHeaderFilter();
} 
```
