### ISSUE TITLE
Make SpringDocHateoasConfiguration conditional on bean LinkRelationProvider instead of class

### ISSUE THREAD

**Issue by tomjankes** [springdoc/springdoc-openapi#1727]
**Is your feature request related to a problem? Please describe.**
- In my application i have `spring-hateoas` in my classpath but it's not initialized. `spring-hateoas` provides `LinkRelationProvider `  interface and some implementations
- SpringDocHateoasConfiguration has conditional `@ConditionalOnClass(LinkRelationProvider.class)` but it actually expects implementation of `LinkRelationProvider` injected as a bean
- I have SpringDocHateoasConfiguration in my classpath because I use springdoc-openapi-data-rest and it pulls springdoc-openapi-hateoas transitively
- To use springdoc I have to manually exclude SpringDocHateoasConfiguration from my SpringBootApplication so that I avoid missing bean error on application startup

**Describe the solution you'd like**
Since `SpringDocHateoasConfiguration` requires bean of type `LinkRelationProvider` to be present to work properly please consider changing the condition from `@ConditionalOnClass` to `@ConfitionalOnBean`.

**Describe alternatives you've considered**
I considered excluding springdoc-openapi-hateoas from springdoc-openapi-data-rest dependency but it requires class `HateoasHalProvider`

**Comment by bnasslahsen** [comment]
@tomjankes,

`@ConfitionalOnBean` breaks the exiting tests.
You should remove `spring-hateoas` from your application if it's not used.
Otherwise, you Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem, so we can if there is other alternatives.
