### ISSUE TITLE
Adding `url` or `configUrl` to the URL no longer pre-loads the config at that URL

### ISSUE THREAD

**Issue by JoshMcCullough** [springdoc/springdoc-openapi#1765]
**Describe the bug**
We pass the `url` parameter to specify the config to load, e.g. `mysite.com/api/swagger-ui/index.html?url=/blah/v3/api-docs`. This worked fine but no longer works. Passing the `url` parameter, or `configUrl` seems to have no affect and we instead see the message:

> Failed to load remote configuration.

**To Reproduce**
- What version of spring-boot you are using? 2.7.1
- What modules and versions of springdoc-openapi are you using? 1.6.9
- What is the actual and the expected result using OpenAPI Description (yml or json)? N/A
- Provide with a sample code (HelloController) or Test that reproduces the problem: N/A

**Expected behavior**
Providing `url` or `configUrl` in the URL should pre-load the Swagger UI with that config.

**Additional Information**
Note that looking at the Developer Tools I see that it is trying to fetch the config from `/v3/api-docs/swagger-config` regardless of what I put in the URL.

**Comment by bnasslahsen** [comment]
@JoshMcCullough, 

There are security resons for that.

Disabled since v1.6.0. This parameter enables (legacy) overriding configuration parameters via URL search params. [See security advisory](https://github.com/swagger-api/swagger-ui/security/advisories/GHSA-qrmm-w75w-3wpx) before enabling this feature.

If you want enable it at your own risks, use `springdoc.swagger-ui.queryConfigEnabled=true`

**Comment by JoshMcCullough** [comment]
It's only a security issue for absolute URLs. It would have made sense to still allow relative URLs, e.g. those that don't match with `^https?`. But, thanks for the workaround.
