### ISSUE TITLE
Tags are generated in reverse alphabetical order

### ISSUE THREAD

**Issue by mbedna** [springdoc/springdoc-openapi#204]
When using `@Tag` annotation for each class, tags in openapi.json are generated in reverse alphabetical order. Is this expected behavior?

Sample:
` {
         "description":"abc",
         "name":"AdministrativeUnitController"
      },
      {
         "description":"abc",
         "name":"AdminController"
      },
      {
         "description":"abc",
         "name":"AccreditationTypeDictController"
      }`

**Comment by springdoc** [comment]
Hi, 

 This is not expected behaviour. 
 You can look at demo 3 where tags are not sorted in alphabetical order:
- https://springdoc-openapi-test-app1-courteous-puku.eu-de.mybluemix.net/swagger-ui/index.html?url=/v3/api-docs&validatorUrl=

 You can have control on the tags order, using OpenApiCustomiser :

```java
@Bean
public OpenApiCustomiser sortTagsAlphabetically() {
    return openApi -> openApi.setTags(openApi.getTags()
            .stream()
            .sorted(Comparator.comparing(tag -> StringUtils.stripAccents(tag.getName())))
            .collect(Collectors.toList()));
}
```
