### ISSUE TITLE
The key of a java.util.Map example value will be generated as additionalProp1, additionalProp2, additionalProp3

### ISSUE THREAD

**Issue by sven-tsi** [springdoc/springdoc-openapi#2040]
**Describe the bug**

The key of a java.util.Map example value will be generated as additionalProp1, additionalProp2, additionalProp3 instead of its defined example value.

It looks like the example value of the responses:
https://petstore.swagger.io/#/store/getInventory and http://158.101.191.70:8081/swagger-ui/index.html#/store/getInventory

**To Reproduce**
Spring Boot 3.0.1
Springdoc 2.0.2:
 - springdoc-openapi-starter-webmvc-api
 - springdoc-openapi-starter-common
 - springdoc-openapi-starter-webmvc-ui

- Provide with a sample code (HelloController) or Test that reproduces the problem: it seems to happen with the official petstore example. Is this also generated with springdoc?

**Expected behavior**
The example value of the key class should be used and not the placeholder additionalProp1, additionalProp2, additionalProp3

**Comment by bnasslahsen** [comment]
@sven-tsi,

As you said, if you are referring to the official petstore example. **This is not generated with springdoc-openapi!**

**Comment by sven-tsi** [comment]
@bnasslahsen your own Example looks the Same: 158.101.191.70:8081/swagger-ui/index.html#/store/getInventory
Is This Not generated With Springdoc?

**Comment by bnasslahsen** [comment]
@sven-tsi,

it's generated with Springdoc. And it's same result as the reference official petstore example ...

**Comment by JosephWitthuhnTR** [comment]
I _think_ what @sven-tsi is that this could behave better when it comes to the key side of a Map. I've run into similar frustration, if I'm understanding his issue correctly.

For example, if I have this in one of my request/response objects

```java
@Schema(description = "This is a map on my request object.")
private Map<TestEnum, String> mapFieldToBeDocumented;
```

With an enum or other type for the key:
```
public enum TestEnum {
  FIRST_OPTION, SECOND_OPTION, THIRD OPTION, FOURTH_OPTION
}
```

Wouldn't it be better for the keys to be called "FIRST_OPTION", "SECOND_OPTION", "THIRD_OPTION" instead of "additionalProp1", "additionalProp2", ... ?

Having said that, I understand this might not be practical. Since the key **must** be a string and example values for arbitrary objects could be all sorts of things that aren't valid JSON (numbers, complex objects, etc...). In short, not all classes you could put in for the key will have nice String-y example values that could be used.

I don't know if this is feasible or not, but I had been following this issue because it was similar to something I had been looking at in my own code.

**Comment by JosephWitthuhnTR** [comment]
Although, since generic types are erased at runtime, I'm not sure if that would even be possible without an underlying change to the Swagger annotations. (thinking about now that I wrote that out...)
