### ISSUE TITLE
springdoc.api-docs.path do not work with swagger-ui 4.9.0

### ISSUE THREAD

**Issue by Beckham007** [springdoc/springdoc-openapi#2063]
**Describe the bug**
As https://stackoverflow.com/questions/71721477/springdoc-swagger-ui-not-using-swagger-config

The problem is with how the springdoc library uses the swagger-ui. They have written some [custom code](https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-common/src/main/java/org/springdoc/ui/AbstractSwaggerIndexTransformer.java#L193) to patch the index.html file returned by swagger-ui jar on the fly to inject the configUrl query param in the response.

Now when swagger-ui moved from 4.8.1 to 4.9.0, they [changed](https://github.com/swagger-api/swagger-ui/compare/v4.8.1...v4.9.0#diff-6cbb7b4fa9f894c496c5eb7b048ea9e29a64dd08bc6ba63efba41610f057c0ee) the index.html file format which broke the custom code written in springdoc.

**To Reproduce**

- What version of spring-boot you are using?
   2.7.5
- What modules and versions of springdoc-openapi are you using?
  1.6.14

**Comment by bnasslahsen** [comment]
@Beckham007,

The change comes for the swagger-ui . There are security reasons for that!

Disabled since v1.6.0. This parameter enables (legacy) overriding configuration parameters via URL search params. [See security advisory](https://github.com/swagger-api/swagger-ui/security/advisories/GHSA-qrmm-w75w-3wpx) before enabling this feature.
