### ISSUE TITLE
Annotation @Parameters is ignored

### ISSUE THREAD

**Issue by petronika** [springdoc/springdoc-openapi#241]
Hi!

According to the specification `@Operation(parameters={...})` can be replaced by `@Parameters(value={...})` annotation, but this annotation is ignored.

There was [the old issue](https://github.com/springdoc/springdoc-openapi/issues/185), but it was closed without any effect.

**Comment by springdoc** [comment]
Hi, 

 For #185, it has been handled.
 You can look at the following test: https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app60/SpringDocTestApp.java 

 If you don't think so, you can add comment and it will be reopened.

For `@Operation(parameters={...})` is also already supported.
  If you have more questions, please provide more information in order to go further:
  - The sample (java) code to reproduce your issue.
  - The result you have got in OpenAPI format
  - The expected Result

**Comment by petronika** [comment]
Hi!

Please see my sample code [here](https://github.com/petronika/springdoc-test).

**Comment by springdoc** [comment]
Hi @petronika , 

 This case was not yet handled.
 It will be part of v1.2.18, of springdoc-openapi.

**Comment by javaHelper** [comment]
Could you please guide me here: https://stackoverflow.com/questions/59967447/how-to-globally-ignore-api-of-spring-boot-from-open-api-3-specification ?
