### ISSUE TITLE
SpringDoc is duplicating all paths under one tag

### ISSUE THREAD

**Issue by rishyrane** [springdoc/springdoc-openapi#2421]
we have just moved from swaggercodegen to openapigenerator and we have also moved to springdoc instead of springfox.

We realized that for all our swagger.json files, the springdoc that we view has one tag in which all other paths are also duplicated.

For e.g.

    Tag1

Path b

    Tag2 (only this tag has a description - The Tag1 api)

Path a

Path b

Path c

Path d

    Tag3

Path d

The api/v3/docs that the ui points to shows Tag1 for Path b and Path d even though such is not the case in the Swagger.json we have created. We have also moved from spring boot 2.5 to spring boot 3.x.

We used useTags under our openapi generator configs, we also tried setting springdoc.auto-tag-classes to false. We also tried adding an empty Tag4 which didnt show up at all.

**Comment by bnasslahsen** [comment]
@rishyrane,

The is no known issues related to tags duplication.
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/296af61ecd2791599266083f2fe5461147adb376/CONTRIBUTING.adoc), [security policy](https://github.com/springdoc/springdoc-openapi/blob/296af61ecd2791599266083f2fe5461147adb376/SECURITY.md), and [code of conduct](https://github.com/springdoc/springdoc-openapi/blob/296af61ecd2791599266083f2fe5461147adb376/CODE_OF_CONDUCT.md).

**Comment by Picazsoo** [comment]
Hello @rishyrane , I would bet your problem is caused by implementing multiple generated RestController interfaces in one implementation. What then happens is that the implemented methods then inherit tags from all the interfaces. Try implementing each interface separately - I expect this will solve you issue. Mind you though, @bnasslahsen is right - this has nothing to do with SpringDoc really - more with the way the tags are generated in the openapi generator plugin.
