### ISSUE TITLE
Extensions in subobjects of OpenAPI no longer work

### ISSUE THREAD

**Issue by ezoerner** [springdoc/springdoc-openapi#2449]
This is closely related to #2104, which states that extensions in the OpenAPI object no longer work.
This was fixed for extensions at the top level, but extension in sub-parts of OpenAPI are also no longer working. One of these sub-objects is the Info object which can also have extensions. I believe there are extensions in other sub-parts that are probably also not working.

I've verified that the extensions of Info are not working in v1.6.8, 1.16.15, and 1.7.0.

**Comment by bnasslahsen** [comment]
@ezoerner,

I have added a fix for it.
Let me know if the fix works for you with the [latest snapshot](https://springdoc.org/#how-can-i-use-the-last-springdoc-openapi-snapshot).

**Comment by bmr-exerp** [comment]
Hi, this change appears to have caused a regression: see https://github.com/springdoc/springdoc-openapi/issues/1655 .

I've encountered a similar problem to the linked github issue, in that I'm trying to serialise a `JsonNullable<T>`. I configure the `ObjectMapperProvider` to use `new JsonNullableModule()`, but that module is ignored because the OpenAPIService uses `new ObjectMapper`.

As a consequence, when I try to create POJO examples programmatically, e.g.

```
	Foo example = new Foo(JsonNullable.of("bar"), JsonNullable.of(null));
	.addExamples("foo", new Example()
			.description("fooBar")
			.summary("fooBarBaz")
			.value(example1))
```

Then the example is serialised as:

```
{
	"bar": {
		"present": true
	}
	"baz": {
		"present": true
	}
}
```

instead of

```
{
	"bar": "bar",
	"baz": null
}
```

I want to use 1.8.0 because of its support for OpenAPI spec version 3.1.0, so this is a major problem for me.
