### ISSUE TITLE
@Parameter 'required' property is always ignored

### ISSUE THREAD

**Issue by glockbender** [springdoc/springdoc-openapi#252]
Code example:

```
@GetMapping(produces = [MediaType.APPLICATION_JSON_VALUE])
    fun getOrders(
        @RequestLimit @Parameter(name = "limit", required = false) limit: Int?,
        @RequestOffset @Parameter(required = false) offset: Int,
        @HeaderUserId userId: UUID,
        @HeaderVisitorId visitorId: UUID
    )
```

But always parameter marks as 'required' in ui and json schema

<img width="813" alt="Снимок экрана 2019-12-11 в 14 54 35" src="https://user-images.githubusercontent.com/16047417/70619517-357de700-1c26-11ea-840e-2b972e8aa298.png">

**Comment by springdoc** [comment]
Hi, 

 This an expected bahaviour. You can have a look at: #14
 - Any @GetMapping parameters should be marked as required, even if @RequestParam missing.

 If you need @GetMapping parameters to be optional, you can use: @RequestParam(required = false)

**Comment by glockbender** [comment]
Ok. Its really correct behaviour. But why @Parameter annotation data ignored? As i understood, swagger-annotations used for implicit declaration or overriding default parser behaviour. If this concept ignored, the usefulness of this library tends to zero

**Comment by little-fish** [comment]
Hi there.
It seems to me that @glockbender 's arguments are right. Explicit swagger annotaion should override default parser behavior.
@springdoc Do you think it will be changed in the future?

**Comment by bnasslahsen** [comment]
Hi @little-fish, 

 For Pageable, are you declaring using ?

-  `@ParameterObject Pageable pageable`

**Comment by little-fish** [comment]
Hi @bnasslahsen,
No, I am not. And that solved my issue! Thank you very much. I missed that in the documentation.

Anyway, I still things that `@Parameter` should override default parser behavior.

Back to my "issue". The problem with nullable `Pageable` object when using `@RequestParam` annotation is because the `org.springframework.web.method.annotation.RequestParamMethodArgumentResolver` is used **before** any other non-annotation resolvers. See the [documentation](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/servlet/config/annotation/WebMvcConfigurationSupport.html#addArgumentResolvers-java.util.List-). This is probably the reason why the `Pageable` parameter is always used without that annotation (in the Spring documentation and all materials I examined). 
What a greate day, I have learnt two new things today ,)

**Comment by W1zzard** [comment]
Problem described by @glockbender still exist, and  **@RequestParam** is not an option, because it override custom resolver by annotation completely, i need to make parameter with custom annotation to be optional and looks like it is impossible.
