### ISSUE TITLE
How to dynamically generate GroupedOpenApi, or dynamically produce groups based on interface tag information

### ISSUE THREAD

**Issue by zxuanhong** [springdoc/springdoc-openapi#2539]
**Is your feature request related to a problem? Please describe.**

1. I hope to dynamically parse the tag information on the interface through RequestMappingHandlerMapping, and then dynamically generate GroupedOpenApi. Currently, no suitable method has been found
2. The purpose of doing this is to have a dynamic interface version management. I hope to dynamically and automatically generate group information for different versions.
3. For example, the following one hopes to parse interface information and automatically generate two groups, and the interface can switch to only display API information for different groups
<img width="1001" alt="image" src="https://github.com/springdoc/springdoc-openapi/assets/62740686/7308cb2a-e7b4-423c-b935-15df42c940ee">

**Comment by codespearhead** [comment]
I'm afraid it's not clear what you're trying to accomplish.

Are you planning to URI version your API? Because [Grouped tags won't lay them out hierarchically in the OpenAPI UI](https://github.com/swagger-api/swagger-ui/issues/3711#issuecomment-332624327), unless you use a [third-party plugin](https://github.com/swagger-api/swagger-ui/issues/5969), which I believe is no longer [initially planned to do](https://github.com/OAI/OpenAPI-Specification/issues/1107), because the OpenAPI spec currently doesn't support URI versioning in the same OpenAPI definition. What it does support is multiple servers, each with it's own URI versioned base path.

You might want to check [this](https://springdoc.org/faq.html#_how_can_i_filter_the_resources_documented_in_the_output_specification_by_the_provided_group) to [this](https://springdoc.org/faq.html#_how_can_i_define_multiple_openapi_definitions_in_one_spring_boot_project).

**Comment by bnasslahsen** [comment]
@zxuanhong,

There is no plan for such a support.
