### ISSUE TITLE
Swagger annotations overrides mvc parsing rules

### ISSUE THREAD

**Issue by glockbender** [springdoc/springdoc-openapi#264]
Continuing #252:
@springdoc Its really correct behaviour. But why @parameter annotation data ignored? As i understood, swagger-annotations used for implicit declaration or overriding default parser behaviour. If this concept ignored, the usefulness of this library tends to zero. As you see in my code snippet, used my own parameter annotations. This an important case to override default request parameter handling.

**Comment by glockbender** [comment]
Another case, when calc parameter needs be override by annotation:

**Comment by springdoc** [comment]
Hi, 

 The sample you are providing is not correct. `@ApiModelProperty` is a swagger-core 1.5 which produces Swagger/OpenAPI 2.0 definitions. 

 You should use: swagger-core 2.X that produces OpenAPI 3.0

 Please don't open many issues on the same topic. You can add your comments on the previous issue and we follow all the comments and we will reopen when its relevant.

 If you have more questions, please provide more information in order to go further:

-  The sample (java) code to reproduce your issue.
- The result you have got in OpenAPI format
- The expected Result
