### ISSUE TITLE
swagger-ui.html vs. static content

### ISSUE THREAD

**Issue by henke77** [springdoc/springdoc-openapi#272]
We configured our app like this:
springdoc:
  swagger-ui:
    path: '/[contextPath]/swagger-ui.html'

Calling swagger-ui leads to 404. However our static content at /[contextPath] is delivered correctly.

The other way around, if we remove the springdoc path config, the swagger-ui can be displayed but the static content is no longer delivered.

**Comment by springdoc** [comment]
Hi, 

 Your existing configuration seems to be in conflict with springdoc-openapi .
 You can just change the path where you serve the swagger-ui, in order not to serve it from the root-path as follow:

```properties
springdoc.swagger-ui.path=/context-path/swagger-path/swagger-ui.html
```

**Comment by Andrew3431** [comment]
Hi @springdoc , I know this discussion has been going on back and forth. I just want to confirm the behavior of springdoc. I had the same issue as @henke77 . I have a static page set at my context path , i.e localhost:8080 has a welcome page. I set `springdoc.swagger-ui.path=/swagger/swagger-ui.html`( in this way the static welcome page at my context path does not throw a 404) Now when I go to `http://localhost:8080/swagger/swagger-ui.html` , this redirects me to `http://localhost:8080/swagger/swagger-ui/index.html?url=/v3/api-docs&validatorUrl=` and displays the swagger-ui page. Is that the expected behavior ? Will the swagger-ui.html always gets redirected to `swagger-ui/index.html?url=/v3/api-docs&validatorUrl=` ?

**Comment by springdoc** [comment]
Hi @Andrew3431,

 Yes, this is the expected behavior.
