### ISSUE TITLE
Providing the community with a 2.x.x-RC1 release

### ISSUE THREAD

**Issue by cagliostro92** [springdoc/springdoc-openapi#2772]
**Is your feature request related to a problem? Please describe.**

- Most of us are early adopters of spring-boot 3.4 because of its new features, breaking changes, and deprecations. Unfortunately,`springdoc-openapi-starter-webmvc-ui 2.6.0` doesn't work with 'spring-boot 3.4.0-RC1`. I saw you have already fixed some major issues, like the one raised in #2771.

**Describe the solution you'd like**

- I would like to have a` 2.x.x-RC1` version. More in general, I think it could be a good practice for this project to link their RC with those of spring-boot.

**Comment by alex-nt** [comment]
It would be highly desirable to keep the releases of this in-sync with latest releases of it's dependencies. The last release was in June, from next year onwards, due to DORA regulation, it would be difficult for us to use it with such a large gap (there are several CVEs brought up by adding the dependency, it is debatable if they impact the application but at the same time that internal debate takes significant time). Any plans for monthly releases? What would be needed to accomplish that?

**Comment by bnasslahsen** [comment]
coming today!
