### ISSUE TITLE
Question: How to remove example values from responses

### ISSUE THREAD

**Issue by Andrew3431** [springdoc/springdoc-openapi#305]
For the api documentation, I just want examples of schema for successful response codes (2XX). For response codes like 3XX, 4XX and 5XX , I do not want the examples to occur. Currently my documentation shows examples for all response codes, is there a way I can remove them ?

**Comment by bnasslahsen** [comment]
If you have an empty content as a response, you can use the following syntax which will hide the related example values: 
` @ApiResponse(responseCode = "404", description = "Thing not found", content = @Content),`

If your response code, has a response with a content, the only possible thing is to change the behaviour of the swagger-ui using the following property. The UI will display the model every where instead of the example value:

```properties
springdoc.swagger-ui.defaultModelRendering=model
```

If this is not enough, you can submit an enhancement on the swagger-ui project:
https://github.com/swagger-api/swagger-ui

**Comment by Andrew3431** [comment]
I had an empty content for response and the example you provided worked perfectly, thanks :)
