### ISSUE TITLE
 calculateServerUrl seems to duplicate context root in Webflux

### ISSUE THREAD

**Issue by davidmelia** [springdoc/springdoc-openapi#31]
Hi,

I'm finding it very difficult to add a context root when working with springdoc.   I've added my example in https://github.com/davidmelia/springdoc-webflux.  

In Webflux I'm using the PathMatchConfigurer to prefix all controllers with /dave as the root.  I've also added the ability for webjars to be prefixed with /dave as well.  So far so good.

Problem is that OpenApiResource.calculateServerUrl calculates the serverBaseUrl as `http://localhost:8080/dave` 
but then in swagger it calls
`http://localhost:8080/dave/dave/tweets`

**Comment by springdoc** [comment]
Hi, 

 The calculated server url is only used for swagger-ui purpose only. And not used to calculate the OpenAPI document.
 If an application is deployed in a container, like a tomcat for example, the server url includes the context-root as well.

 spring-webflux doesn't support for the moment context-paths:
- https://github.com/spring-projects/spring-boot/issues/14082
- https://github.com/spring-projects/spring-boot/issues/10129#issuecomment-351953449

In order to make, your example work with context-path, you can use the attached configuration.

The following pull request, can help you make context-path work:

- https://github.com/davidmelia/springdoc-webflux/pull/1
