### ISSUE TITLE
Swagger UI not available since v1.21 with springdoc.api-docs.enabled=false

### ISSUE THREAD

**Issue by drapej** [springdoc/springdoc-openapi#321]
Hi, 

Since the v1.21 we can't see the swagger-ui interface
We use Spring boot so we have this parameters in the application.properties :
```
## Our own yaml file
application.api.file = my_api.yaml

## Disable automatic yaml file
springdoc.api-docs.enabled=false
## Url of the static page to show swagger-ui interface
springdoc.swagger-ui.path=/${application.api.name}/doc/index.html
## Default Url use in the swagger interface
springdoc.api-docs.path=/${application.api.name}/doc/openapi.yaml
```
We write our own .yaml file.
We access to swagger interface by using the url _${application.api.name}/doc/index.html_
We have also a controller to deliver our own yaml file 
```
@RestController
class DocController(val application: String) {

    @Value("classpath:\${application.api.file}")
    private lateinit var resourceFile: Resource

    @GetMapping(path = ["/{applicationName}/doc/openapi.yaml"], produces = [Constants.APPLICATION_OPENAPI_YAML])
    @ExceptionHandler(UrlNotFoundException::class)
    @ResponseBody
    fun apiDoc(@PathVariable applicationName: String): String {
        if (applicationName != application) {
            throw UrlNotFoundException()
        }
        return Scanner(resourceFile.inputStream, StandardCharsets.UTF_8.name()).use { scanner ->
            scanner.useDelimiter("\\A").next()
        }
    }
}
```

Until the v1.20, all works perfectly but since v1.21 not. 
The url ${application.api.name}/doc/index.html is unknown.

Indeed, since the v1.21, class SwaggerConfig and SwaggerWelcome are load only if OpenAPIBuilder exist, but it's not true because we have _springdoc.api-docs.enabled=false_ and so the SpringDocConfiguration is not load (who is in charge to load the OpenAPIBuilder).
Is it normal and desired or few regression ?
If it's normal, how we can do now ? 

Thank you for your help

**Comment by bnasslahsen** [comment]
Hi, 

 Yes this the desired configuration. You can have a look at: #294. 
  - When you set `springdoc.api-docs.enabled=false`, all the springdoc-openapi configuration beans will be disabled.

The springdoc-openapi-ui is based on the springdoc-openapi configuration beans. If they are not present, it shouldn't be loaded.

 Frankly, we didn't expect that some projects might use the springdoc-openapi-ui instead of the swagger-ui to serve static OpenAPI definitions.

You can then declare your own SpringDocConfiguration Bean, which will enable only the ui using v1.2.24:
```
@Bean
SpringDocConfiguration springDocConfiguration(){
	return new SpringDocConfiguration();
}
```
Or, you can just use swagger-ui webjars directly, if you are loading only static files.

**Comment by sdoeringNew** [comment]
> Frankly, we didn't expect that some projects might use the springdoc-openapi-ui instead of the swagger-ui to serve static OpenAPI definitions.

For sake of completeness we use static Swagger / OpenAPI definitions, too.
It's not just a single case.

We write the interface specification manually but generate all other stuff out of it. Models, Springs Controllers / Delegates / Services, Feign Clients, other clients for different languages, ...
