### ISSUE TITLE
Support for @RequestParam for file upload

### ISSUE THREAD

**Issue by silentsnooc** [springdoc/springdoc-openapi#377]
The docs for my multipart file-upload endpoint do not seem to get generated correctly.

For this

```java
@RequestMapping(value = "/tracks", method = RequestMethod.POST, consumes = {MediaType.MULTIPART_FORM_DATA_VALUE})
public @ResponseBody
String postTrack(
        @RequestParam("file") MultipartFile file
) {
    storageService.store(file);
    return "redirect:/";
}
```
The generated documentation results in

![image](https://user-images.githubusercontent.com/1429426/73133745-54490900-402d-11ea-935f-afcb18b69d70.png)

This are my maven dependencies:

```xml
<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-core</artifactId>
    <version>1.1.49</version>
    <exclusions>
        <exclusion>
            <groupId>io.github.classgraph</groupId>
            <artifactId>classgraph</artifactId>
        </exclusion>
    </exclusions>
</dependency>

<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-ui</artifactId>
    <version>1.1.49</version>
</dependency>

<dependency>
    <groupId>io.github.classgraph</groupId>
    <artifactId>classgraph</artifactId>
    <version>4.8.44</version>
</dependency>
```

Running under Spring Boot 2.2.2.RELEASE

Am I missing something or is this broken?

This should've been fixed according to https://github.com/springdoc/springdoc-openapi/issues/75

**Comment by bnasslahsen** [comment]
The cause for the issue is different from #75. `@RequestParam` for sending files was not yet handled.
The support for `@RequestParam` for sending files will be available  in the next release. v1.2.29.
As a workaround you can remove `@RequestParam`("file")  or use `@RequestPart`("file") instead:  tested with` v1.2.28`;

Note also, you don't need to declare, both dependencies springdoc-openapi-ui and springdoc-openapi-core: springdoc-openapi-core is by transitivity included in  springdoc-openapi-ui.

**Comment by silentsnooc** [comment]
@bnasslahsen Thank you for clarification! Indeed it worked with `@RequestPart`! Thank you for also mentioning the redundant dependency!
