### ISSUE TITLE
Question: How to declare a parameter `in` value as "formData" ?

### ISSUE THREAD

**Issue by Andrew3431** [springdoc/springdoc-openapi#380]
```java
    public Customer customerInfo(
            @Parameter(description = "the customer id value", required = true)
            @RequestParam String id)
```
For the above code, by default the "parameters"  section in v3/api-docs is generated as 
```json
       "parameters": 
          {
            "name": "id",
            "in": "query",
            "description": "the customer id value",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
```
I want the `in` value to be generated as `formData`. The enum values for `ParameterIn` class does not have a value for FormData. What should be used in this case ?

**Comment by bnasslahsen** [comment]
Hi @Andrew3431, 

 Please have a look at the documentation of OpenAPI 3. Use @RequestBody instead.
 
- OAS 3.0 introduced a number of changes to how the body of a request and a response can be defined. One significant change is that body and formdata parameters have been removed and replaced with **requestBody**. The requestBody is more flexible in that it lets you consume different media types, such as JSON, XML, form data, plain text, and others, and use different schemas for different media types.

Also, please have at our contribution guide, on the following section: Using GitHub Issues. Because this kind of questions should go to stackoverflow:
- https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc
