### ISSUE TITLE
Support running in subpath

### ISSUE THREAD

**Issue by johndevs** [springdoc/springdoc-openapi#391]
Hi, 

We are running our Spring Boot app in a subpath provided by our loadbalancer. This doesn't seem to work with springdoc as all relative paths are invalid since the spring boot app thinks it is running under root. 

Is there any way to support this? e.g. via providing a property that just changes the relative paths, not relocates the controller path?

We have successfully been using springfox which supports this but we haven't find a way to do the same with this library. We'd like to move over if this is possible.

**Comment by bnasslahsen** [comment]
Hi @johndevs, 

 Your description is not clear, so it can be addressed.

 - Can you be more specific, providing samples of paths working on your app and not working on you loadbalancer?
 - What are the properties of springdoc-openapi you are using?
 - What version of springdoc-openapi?
 - What do you mean by providing a property that just changes the relative paths ?

**Comment by johndevs** [comment]
@bnasslahsen 

Sure, sorry if I wasn't clear.

So our Spring Boot application is running on a server on the root path, for example `http://internal.server:8080/`. If I request swagger UI via `http://internal.server:8080/swagger-ui.html` everything works fine.

Publicly though our load balancer re-maps the server url so our Spring Boot application can be accessed via `http://public.server/myapp`. Now if I try to get `http://public.server/myapp/swagger-ui.html` it doesn't work anymore.

The swagger-ui.html now redirects to `/*` instead of `/myapp*` and the documentation doesn't load.

**Comment by bnasslahsen** [comment]
Hi @johndevs, 

 You didn't precise:
- What are the properties of springdoc-openapi you are using?
- What version of springdoc-openapi and spring-boot you are using?

 Anyway, have a look at the documentation. 
 Your application should declare the right properties and sometimes ForwardedHeaderFilter as well depending on your configuration : 
- https://springdoc.github.io/springdoc-openapi-demos/faq.html#how-can-i-deploy-the-doploy-springdoc-openapi-ui-behind-a-reverse-proxy

 Make sure also, your loadbalancer is forwarding the right headers: X-Forwarded-For and X-Forwarded-Prefix, or any equivalent depending on the solution you are using.

 Make sure you are using the last stable version: v1.2.29:

**Comment by johndevs** [comment]
Hi, 

Thanks for the pointer to `X-Forwarded-Prefix` which we were missing. We added that header to the load balancer and everything seems to work. :+1:

**Comment by agurskyi** [comment]
We have a similar problem on the **AWS** server as @johndevs described.

"So our Spring Boot application is running on a server on the root path, for example http://internal.server:8080/. If I request swagger UI via http://internal.server:8080/swagger-ui.html everything works fine.

Publicly though our load balancer re-maps the server url so our Spring Boot application can be accessed via http://public.server/myapp. Now if I try to get http://public.server/myapp/swagger-ui.html it doesn't work anymore.

The swagger-ui.html now redirects to /* instead of /myapp* and the documentation doesn't load."

We have a WebFlux application, use Spring Boot 2.3.1.RELEASE, springdoc-openapi version: v1.4.8

application.yaml configuration:
......
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json
server:
  forward-headers-strategy: framework
......

Unfortunately, AWS doesn't allow to set **X-Forwarded-Prefix** prefix

**Comment by bnasslahsen** [comment]
@agurskyi, 

 These are standard http headers...
 Do you have the reference in the AWS documentation, that states setting  **X-Forwarded-Prefix** is not allowed ?

**Comment by agurskyi** [comment]
We use AWS Network Load Balancers https://docs.aws.amazon.com/elasticloadbalancing/latest/network/introduction.html. It doesn't allow to set HTTP headers.
AWS Classic Load Balancer allows configuring 3 X-Forwarded headers. More details here - https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html

**Comment by bnasslahsen** [comment]
@agurskyi, 

 Exactly, so AWS allows setting **X-Forwarded-Prefix** header, and for that you should use the right service.

**Comment by bnasslahsen** [comment]
@agurskyi,

Exactly, so AWS allows setting X-Forwarded-Prefix header, and for that you should use the right service.
