### ISSUE TITLE
How to add response model ref using spring doc when using custom openAPI?

### ISSUE THREAD

**Issue by Jacob-cheng-2412** [springdoc/springdoc-openapi#417]
Hi, I am trying to create a custom openapi documentation for the endpoints provided by spring security library. I am trying to add a response model reference to one of the response messages, but I am unable to find the schema setting there.

```java
 .responses(new ApiResponses()
      .addApiResponse("200", new ApiResponse().description("OK")
              .content(new Content().addMediaType(
                    org.springframework.http.MediaType.APPLICATION_JSON_VALUE, new MediaType())))
      .addApiResponse("400", new ApiResponse().description("The request is invalid."))
```

I need to add a response model
`org.springframework.security.oauth2.common.exceptions.OAuth2Exception`ref to "400" status code. How can I achieve that ?

**Comment by bnasslahsen** [comment]
Hi @Jacob-cheng-2412,

Please have at our contribution guide, on the following section: Using GitHub Issues. Because this kind of questions should go to stackoverflow:

https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc
We use GitHub issues to track bugs and enhancements. If you have a general usage question please ask on Stack Overflow.
The springdoc-openapi team and the broader community monitor the springdoc tag.

**Comment by kevinpeter** [comment]
You need to set the Schema to the `MediaType`. For example:

```java
MediaType mediaType = new MediaType();

Schema<?> schema = new Schema<>();
schema.set$ref("#/components/schemas/youSchemaName");
mediaType.setSchema(schema);

  
....
 .responses(new ApiResponses()
      .addApiResponse("200", new ApiResponse().description("OK")
              .content(new Content().addMediaType(
                    org.springframework.http.MediaType.APPLICATION_JSON_VALUE, mediaType)))
      .addApiResponse("400", new ApiResponse().description("The request is invalid."))
```
