### ISSUE TITLE
Unable to generate header in api call when using @RequestHeader

### ISSUE THREAD

**Issue by Andrew3431** [springdoc/springdoc-openapi#425]
I need to allow the user to enter the bearer token in the parameter section which will be sent in header when the call is made 

```java
@Operation(summary = "userdata")
    @ApiResponses(value = {@ApiResponse(responseCode = "200", description = "ok " )})
    @RequestMapping(method = RequestMethod.GET, produces = APPLICATION_JSON_VALUE)
    @ResponseBody
    public Map<String, Object> getUserData(
            @Parameter(description = "Access token in Bearer format")
            @RequestHeader("Authorization") String authHeader) 
```

json value is 
```json
"parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "Access token in Bearer format i.e. 'Bearer X' where X is  access token",
            "required": true,
            "schema": {
              "type": "string"
            }
        }
]
```
The access token value entered in Parameter , is not getting sent to Header as "Authorization". The curl command created by swagger is `curl -X GET "http://localhost:8080/openid/userdata" -H "accept: application/json" `

I want the curl command to generated as `curl -X GET "http://localhost:8080/oidc/userinfo" -H "Authorization: Bearer XXX" "accept: application/json"` where `Bearer XXX` is the value entered in Parameter. Is it possible to achieve this without sending the access token via security requirement ?

**Comment by bnasslahsen** [comment]
Hi @Andrew3431, 

 Your question is already answered here:
 - https://github.com/springdoc/springdoc-openapi/issues/49
 
 Use @SecurityRequirement and respect the OpenAPI specification syntax, and it should work.
 - https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md


 Next time, please have a look at our contribution guide, on the following section: Using GitHub Issues. Because this kind of questions should go to stackoverflow:

- https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc
We use GitHub issues to track bugs and enhancements. If you have a general usage question please ask on Stack Overflow.
The springdoc-openapi team and the broader community monitor the springdoc tag.

**Comment by Andrew3431** [comment]
@bnasslahsen I am able to pass the header value through the Authorize button on the top right corner of the swagger UI (I use that for all my other apis which I need to be protected with a security header). My question was, is there a way to send the header value through the `@Parameter` tag. I have tried with defining a security requirement through cutomOpenAPI and then adding a `@SecurityRequirement` to operation. Please find the below screenshot
![image](https://user-images.githubusercontent.com/58496081/74782136-c640f680-5257-11ea-8c29-b60b538c8eb9.png)

The header value does get passed through if sent using the Authorize button but not when sent in @Parameter tag.
The same question was asked in one of the comments in #49. Questions about these are not getting any replies in stack overflow. Thats why I am posting it over here.

**Comment by bnasslahsen** [comment]
@Andrew3431, 

 The behaviour you are describing is not related to springdoc-openapi. But to swagger-ui:
 - https://github.com/swagger-api/swagger-ui/issues/5715

 The specification does not allow explicitly adding Authorization header. For more information, please read:
 - https://swagger.io/docs/specification/describing-parameters/#header-parameters.

**Comment by Andrew3431** [comment]
Thank you @bnasslahsen
