### ISSUE TITLE
Only extend defined ApiResponses with generic responses from controller advice

### ISSUE THREAD

**Issue by m-kay** [springdoc/springdoc-openapi#429]
The responses generated from a controller advice are currently added to every operation. However in some cases it is impossible to get this error/response on a certain operation. Therefore I would suggest to only add all generic responses if no `@ApiResponse` annotation is present on an operation. If there are `@ApiResponse` annotations on an operation I would only extend this config with the generated generic response so one could configure which of the generic responses are shown for which operation.

**Comment by bnasslahsen** [comment]
Hi @m-kay,

The following property will be available on v1.2.32:

```properties
springdoc.override-with-generic-response=false
```
It will allow you to:
- Only add all generic responses if no @ApiResponse annotation is present
- If there is an @ApiResponse annotations prensent on an operation, it will be used instead as reference

**Comment by m-kay** [comment]
Thanks @bnasslahsen 

This is already helpful but not completely what I was expecting. What I meant by "enhancing" was that if  there is a generic response with schema lets say for response code 400 and I have the annotation  `@ApiResponse(responseCode = "400", description = "BAD_REQUEST")` on my operation then also add the generic response schema.

**Comment by bnasslahsen** [comment]
Hi @m-kay, 

I had a doubt that you also, wanted to merge the @ApiResponse from the RestController with the one from @ControllerAdvice. I just didn't want to go further, because it was going to add more complexity and wasn't sure about your requirement.
You can propose your PR and we will integrate it.

**Comment by OmarHawk** [comment]
mh, seems like it never made it into the library. 

I'd like to also have such a feature, where @ControllerAdvice are scanned for corresponding status codes, so that the Schema is merged into the appropriate @ApiResponse, if no schema is defined there - so that you don't have to repeat the very same @Schema with @Content and so on all over again and again, without having too many (irrelevant) error codes in the final docs.

@bnasslahsen: Do you think it makes sense to at least open a separate issue for that?

**Comment by bnasslahsen** [comment]
@OmarHawk, 

There is no need to open a separate ticket. 
As suggested earlier, just submit your PR.
