### ISSUE TITLE
Duplicated documentation generation

### ISSUE THREAD

**Issue by aoudiamoncef** [springdoc/springdoc-openapi#472]
Hi @bnasslahsenb, 

When i annotate my controller class like this: `@RequestMapping(value = {"${app.endpoint}", "${app.prefix}${app.endpoint}"})` the documentation is duplicated. 

I haven't this issue with SpringFox, so i think that's possible to implement it.

Thanks

**Comment by bnasslahsen** [comment]
Hi @aoudiamoncef, 

 This is the expected behaviour. as you are exposing two endpoints.
 If you need only one of the two generated endpoints, you can use OpenApiCustomiser:
 - https://springdoc.github.io/springdoc-openapi-demos/faq.html#how-can-i-customise-the-openapi-object-

 Please, read our contribution guide, on the follwing section **Using GitHub Issues**:
- https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc
