### ISSUE TITLE
Adding classname in examples if can be determined by @JsonTypeInfo

### ISSUE THREAD

**Issue by ddcruver** [springdoc/springdoc-openapi#514]
If the @JsonTypeInfo is defined as:
`@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "@class")`

How can I make the example shown in swagger-ui contain this classname?  It seems like it can be interpreted at runtime.

**Comment by bnasslahsen** [comment]
@ddcruver, 

 If this is your questino: You can use JsonTypeInfo.Id.NAME. There is no relation with springdoc in your description!

Anyway, please have a look at our contribution guide, on the following section: Using GitHub Issues. Because this kind of questions should go to stackoverflow:

- https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc

We use GitHub issues to track bugs and enhancements. If you have a general usage question please ask on Stack Overflow.

The springdoc-openapi team and the broader community monitor the springdoc tag.
