### ISSUE TITLE
Support for OpenAPI 3.0.3

### ISSUE THREAD

**Issue by ddcruver** [springdoc/springdoc-openapi#522]
Looking at the release notes I have not found an instance where the spec would need to be generated differently.  It seems to be the spec was better defined and examples where updated.

If so could we update the spec to set the version to 3.0.3?

Also it would be helpful if we could force it to a earlier or later version, potentially limited to it being part of the same major and minor version of what is being generated.

i.e. the library is generating 3.0.1, allow us to set it manually to 3.0.x.

**Comment by bnasslahsen** [comment]
@ddcruver,

 You have access to the OpenAPI object programmatically using OpenAPI

Here is a sample code for it:

```java
	@Bean
	public OpenApiCustomiser openApiCustomiser() {
		return openApi -> openApi.setOpenapi("3.0.3");
	}
```

 Please note, we do not advise to change the version of OpenAPI, because the consistency between version of the spec and attributes of the specification is guaranteed using swagger-core.
