### ISSUE TITLE
Do you support method level Spring Security / OAuth / Client Credentials

### ISSUE THREAD

**Issue by SledgeHammer01** [springdoc/springdoc-openapi#527]
Hi,

I am currently on Springfox, but as that project seems dead, looking to move here. I am using OAuth / Client Credentials flow and method level security in even the same controller through @PreAuthorize("#oauth2.hasScope('Any')") annotations.  Do you guys support that?

Thanks!

**Comment by bnasslahsen** [comment]
You can use the oauthFlowObject:

- https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#oauthFlowObject

Please have a look at our contribution guide, on the following section: Using GitHub Issues. Because this kind of questions should go to stackoverflow:

- https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc

We use GitHub issues to track bugs and enhancements. If you have a general usage question please ask on Stack Overflow.

The springdoc-openapi team and the broader community monitor the springdoc tag.
