### ISSUE TITLE
How to display a drop-down or a way to select an input from multiple inputs?

### ISSUE THREAD

**Issue by javaHelper** [springdoc/springdoc-openapi#535]
How to display a drop-down or a way to select an input from multiple inputs? 

My organization allows only 8 query parameters to send, we're using pagination, so page, size, sort (by multiple fields) and order (multiple fields). This all consumes 4 query Parameters and left only 4 to used, since for few of the endpoints, consumer wants to use many parameters as optional to fetch the data.

If somehow in api-doc if I can create option to select multiple things like Pagination and Sorting into multi-select checkbox  then it will be great.

I dont see anything in spring doc to do so, any quick help on this ?

**Comment by bnasslahsen** [comment]
Anyway, please have a look at our contribution guide, on the following section: Using GitHub Issues. Because this kind of questions should go to stackoverflow:

- https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc

We use GitHub issues to track bugs and enhancements. If you have a general usage question please ask on Stack Overflow.

The springdoc-openapi team and the broader community monitor the springdoc tag.

**Comment by javaHelper** [comment]
I usually see no response on the stackover (SO) flow questions. Its keep opening more than months and so.

I request you to please provide answers on all the SO questions, so that we wont feel need to add questions here.

I hope you understand this.

Could you please respond here: https://stackoverflow.com/questions/61012882/springdoc-openapi-is-there-any-way-to-override-default-value-as-null-or-empty ?
