### ISSUE TITLE
api-docs controller not work when using path prefix for RestController annotation

### ISSUE THREAD

**Issue by unknowedNp** [springdoc/springdoc-openapi#635]
**Describe the bug**
I have WebMvcConfigurer and customized my rest controller prefix api 
`
configurer.addPathPrefix("/api", HandlerTypePredicate.forAnnotation(RestController.class))
`
when i removed prefix everything is fine and worked, and problem has for swagger-ui cant find /v3/api-doc becase of real address is /api/v3/api-doc.

**To Reproduce**
- What version of spring-boot you are using? 2.2.6
- What modules and versions of springdoc-openapi are you using? springdoc-openapi-ui
- What is the actual and the expected result using OpenAPI Description (yml or json)? no cutomized

**Comment by bnasslahsen** [comment]
Not enough information to address the issue.
If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible :You can have a look at the section Using GitHub Issues.
- https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc

This ticket will be closed, and there is no need to reopen a new ticket for the same issue. 
You can add your comments if needed and we will follow it.

**Comment by brunodelucia82** [comment]
Thank you so much @unknowedNp ! 

I was getting an error due to a 404 response when trying to generate openapi.json via the **springdoc-openapi-maven-plugin**. 

I've been banging my head on the wall for days and finally I've been able to figure out the reason of the problem. 

I had all my rest endpoints urls programmatically prepended "/api" through a custom WebMvcConfigurer in the following way, which is the same thing you did, as far as I can tell from your post: 

```
@Configuration
public class WebConfig implements WebMvcConfigurer {

	public static final String API_PREFIX = "/api";

	@Override
	public void configurePathMatch(PathMatchConfigurer configurer) {
		configurer.addPathPrefix(API_PREFIX,
				HandlerTypePredicate.forAnnotation(RestController.class));
	}

}
```

I could not imagine that this would affect the apiDocsUrl as well. The workaround for this problem was to configure the plugin like this in my pom.xml: 
```
<configuration>
    <apiDocsUrl>http://localhost:8080/api/v3/api-docs</apiDocsUrl>
</configuration>

```
Now the openapi.json file is being generated correctly. 
An alternative solution would be to change the PathMatchConfigurer so that it doesn't affect the apiDocsUrl, but I'm working on it yet.
