### ISSUE TITLE
Incorrect input schema when multiple method params are used

### ISSUE THREAD

**Issue by ayzenquwe** [springdoc/springdoc-openapi#700]
**Describe the bug**
Generated schema includes all method parameters as "body" parameter, although it should include only `@RequestBody` parameter.

**To Reproduce**
A simple rest controller with a single method:
`
    @RequestMapping(method = RequestMethod.POST)
    public ResultDto doSomething(Device device, @RequestBody @Valid SomeDto dto)
`
Device is a bean parsed from a request by `DeviceHandlerMethodArgumentResolver`, but instead of Device, there can be any other dynamically injected types (like custom types related to security, etc).

Generated schema includes Device, although it shouldn't, as only SomeDto is annotated with `@RequestBody`:
```
{
  "device": {
    "normal": true,
    "mobile": true,
    "tablet": true,
    "devicePlatform": "IOS"
  },
  "dto": {
    "foo": "string",
    "bar": "string"
  }
}
```

**Expected behavior**
Generated schema should include only `@RequestBody` parameter.

I tried to check the documentation, but haven't found anything related to this problem. Am I missing something?

**Comment by bnasslahsen** [comment]
@ayzenquwe, 

 You can combine `@ParameterObject` **Device device** using v1.4.0.

`@RequestMapping(method = RequestMethod.POST) public ResultDto doSomething(@ParameterObject Device device, @RequestBody @Valid SomeDto dto)`

If it doesn't answser your request. You can add more details about your expected OpenAPI genereated api-docs.

**Comment by ayzenquwe** [comment]
Thanks for your quick response!

Although `@ParameterObject` works, I'd like to continue the discussion.

I don't fully understand why the library tries to put **all** parameters into the body schema. As far as I know, Spring will parse only `@RequestBody` parameter. These additional parameters are just [MVC Method Arguments](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-ann-arguments) and aren't a part of a body parameter. Also some of them the library already ignores (like, HttpServletRequest). 

Regarding `@ParameterObject`, I don't really like the idea of adding direct dependencies to the library into our controllers. We have lots of custom MVC Method Arguments and the annotation will just clutter method definitions.

So my main question is why the library puts not only `@RequestBody` parameter into the body schema, but all other parameters too.

**Comment by ayzenquwe** [comment]
Also, if I use `@Operation` directly with `content = @Content(schema = @Schema(implementation = SomeDto.class)` it will still generate the body schema with Device class in it, which is quite strange.

**Comment by bnasslahsen** [comment]
@ayzenquwe, 

 To answer you first question; There are other cases where we have to pass parameters as request Body even we don't have the spring annotation `@RequestBody`. For example @RequestPart with files, 

  Your use case is not a common usage of POST Method: You pass an object without any annotation and assume implicitly all the parameters need to be exploded as query params. (Even its handled correctly with spring).

 Also the you need to note that with OpenAPI 3, for POST Methods, it only accepts your objects as swagger `@RequestBody`. 

 In general, for other parameters, the common usage is to add spring annotations for example @RequestParam or @PathVariable, which make the code clear et easy for springdoc to handle.

 For your second question, if you want to just generete correct OpenAPI documentation for your use case using only the declaration of @Parameters using `@Operation` annotation, you will not be able to get your case because as explained, with post you can only pass @RequestBody type. Or Add Parameters as Query / Path or Header Params: 
 - This is the only possible way with the current version of the spec.  

 The usage of @ParameterObject in your case is good fit, to make things work simply. 
 We can think of some automatic transformation, for this case but this might add a lot of complexity for a non common use case. 

 You can also contribute and propose a PR, if you feel you have a better proposal for this case.

**Comment by ayzenquwe** [comment]
Thanks for the explanation.

I didn't understand this part:
> Your use case is not a common usage of POST Method: You pass an object without any annotation and assume implicitly all the parameters need to be exploded as query params. (Even its handled correctly with spring).

This is not related to query parameters, instead it's very similar to HttpServletRequest: those parameters are helpers. They aren't part of API. For example, we pass Security Principal the same way:
`@PostMapping public ResultDto doSomething(@RequestBody SomeDto dto, @LoggedUser User user)`
where @LoggedUser is simply `@AuthenticationPrincipal`. And of course we don't want to see it inside the body schema.

We can also pass some additional classes that are based on current context. And again these are not really a part of a request, but a simple automation of some repeated logic.

As far as I understand, if the library finds a parameter with `@RequestBody`, then it shouldn't include any other parameters into the body scheme. Are there any cases that won't work with this logic?

**Comment by bnasslahsen** [comment]
The parameters like HttpServletRequest are standard spring properties and ignored by springdoc.

You can have a look at the list here:
- https://springdoc.org/faq.html#what-are-the-ignored-types-in-the-documentation

If you have some classes that are not spring and you want to hide:
- https://springdoc.org/faq.html#how-can-i-hide-a-parameter-from-the-documentation-

Or programatically using:

```java
SpringDocUtils.getConfig().addRequestWrapperToIgnore
```

For your question: As far as I understand, if the library finds a parameter with @RequestBody, then it shouldn't include any other parameters into the body scheme. Are there any cases that won't work with this logic? 
 - As answered before: Yes there are other cases: **@RequestPart of MultipartFile/FilePart for example.**

**Comment by ayzenquwe** [comment]
Thanks!

> SpringDocUtils.getConfig().addRequestWrapperToIgnore
This is exactly what I was looking for. Will try it. Thanks.

Regarding multipart requests, not sure how they are related to methods with `@RequestBody` annotation. Is it possible to have @RequestPart params with @RequestBody parameter in a single method?

**Comment by bnasslahsen** [comment]
It depends on which ` @RequestBody` annotation your are refering to!
If the swagger annotation yes. 
You need to note, tat even we have a parameter with @RequestPart, it will be interpreted as @RequestBody from swagger perspective. (Even there no spring @RequestBody annotation)

**Comment by ayzenquwe** [comment]
I was talking about Spring @RequestBody, sorry for confusion. :)
