### ISSUE TITLE
Add Support of Actuator endpoints using webflux

### ISSUE THREAD

**Issue by ivangfr** [springdoc/springdoc-openapi#713]
Hi! I am using **Spring Boot** version `2.3.0.RELEASE` and `springdoc-openapi-webflux-ui` version `1.4.0`.

I've spent some time investigating it and I based on this (https://github.com/springdoc/springdoc-openapi-demos/commit/aa6bcf1f0312c8fc36f94aeb4653718b36c308f6). I did all the normal setup but it's still not showing.

As far as I understood, you need:

1. Actuator dependency
   ```
   <dependency>
     <groupId>org.springframework.boot</groupId>
     <artifactId>spring-boot-starter-actuator</artifactId>
   </dependency>
   ```

2. In your properties, you must actuator `enable`
   ```
   springdoc:
     show-actuator: true
   ```

3. Create a `GroupedOpenApi` to the actuator
   ```
   @Bean
   public GroupedOpenApi actuatorApi() {
      return GroupedOpenApi.builder().group("actuator").pathsToMatch("/actuator/**").build();
   }
   ```

However, I am still having

<img width="1278" alt="Screen Shot 2020-06-06 at 19 50 02" src="https://user-images.githubusercontent.com/10564548/83952256-85cdae80-a82f-11ea-8b7c-6230c5461352.png">

Here is my `SpringDocOpenApiConfig`
```
package com.mycompany.productapi.config;

import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springdoc.core.GroupedOpenApi;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class SpringDocOpenApiConfig {

    @Value("${spring.application.name}")
    private String applicationName;

    @Bean
    public OpenAPI customOpenAPI() {
        return new OpenAPI()
                .components(new Components())
                .info(new Info().title(applicationName));
    }

    @Bean
    public GroupedOpenApi customApi() {
        return GroupedOpenApi.builder().group("api").pathsToMatch("/api/**").build();
    }

    @Bean
    public GroupedOpenApi actuatorApi() {
        return GroupedOpenApi.builder().group("actuator").pathsToMatch("/actuator/**").build();
    }

}
```

What is still missing? Thanks!

**Comment by bnasslahsen** [comment]
Hi @ivangfr, 

The support for spring-boot-actuator endpoints was not yet implemented for webflux as there was not requirements.
We will start supporting it, from v1.4.1 of springdoc-openapi.

This feature is already added to master and you can test with the latest snapshot.

In order to display them, you will need to just follow the steps you have described.

**Comment by MosheElisha** [comment]
First, that you for this. Very helpful.

I noticed a related issue when enabling the feature. I have a test that is meant to check that the api-docs endpoint is working properly.

The test sends an HTTP request to the api-docs path and reads the response into io.swagger.v3.oas.models.OpenAPI.
After upgrading to v1.4.1, the test fails because of an internal validation inside swagger-models-2.1.2 - https://github.com/swagger-api/swagger-core/blob/v2.1.2/modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/Schema.java#L551

The `additionalProperties` is a LinkedHashMap.

![image](https://user-images.githubusercontent.com/1391335/84263128-93cd4900-ab27-11ea-914c-3a2abc060237.png)
