### ISSUE TITLE
OKTA-Spring doc 95% complete integration

### ISSUE THREAD

**Issue by raghuraman1** [springdoc/springdoc-openapi#715]
Hi @bnasslahsen 

I have created a small code at https://github.com/teq-niq/spring-okta-springdoc
It attempts a spring, okta , springdoc integration. I also referred to the keycloak working sample.

Please see the readme.

I think I am almost done when I try using springdoc.swagger-ui.oauth.use-basic-authentication-with-access-code-grant=true in application.properties.
Trouble is it in that scenario it rejects the clientId presence in posted formdata.
Tried a few other things also.

There are some differences in how swagger-ui and the spring code does the processing.
I tried studying those aspects and other details by adding some extra debugging.
There is a debugging filter and it also traces outgoing http calls amongst other debugging efforts.

Hope you can look into it and give some suggestions. 

R

**Comment by bnasslahsen** [comment]
@raghuraman1, 

 I have seen the baeldung settings. These are for the spring-boot application.
 When you add use-basic-authentication-with-access-code-grant, okta complains as doesn't accept it.

 In order to be able to make calls from the swagger-ui, you need to declare à new application in Okta as SPA:
 - https://developer.okta.com/blog/2019/08/22/okta-authjs-pkce

 And then enable PKCE on swagger-ui, so the code_verifier is also sent.
 Here is the complete springdoc-openapi settings for that:

```properties
springdoc.swagger-ui.oauth.client-id=yourSPAClientId
springdoc.swagger-ui.oauth.additional-query-string-params.state=xyz
springdoc.swagger-ui.oauth.additional-query-string-params.nonce=abc
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
springdoc.oAuthFlow.authorizationUrl=${okta.client.orgUrl}/oauth2/v1/authorize
springdoc.oAuthFlow.tokenUrl=${okta.client.orgUrl}/oauth2/v1/token
```

**Comment by raghuraman1** [comment]
Thanks. I will try it and let you know. Meanwhile it makes sense to treat it as new okta SPA config even though technically its  served from same back end app because the html and javascript is totally static. I should have thought of that.

**Comment by raghuraman1** [comment]
It worked. Thanks a lot. I was nearly there. :)

**Comment by raghuraman1** [comment]
Hi @bnasslahsen,
The basics are in place.  Will explore this further and improve the example- especially on the java ie non swagger side.
Thanks again.
Raghu
