### ISSUE TITLE
Always generate yaml/json with the same element order

### ISSUE THREAD

**Issue by kemalizing** [springdoc/springdoc-openapi#857]
**Is your feature request related to a problem? Please describe.**
We are using springdoc to generate openapi yaml files from kotlin code (for this feature language doesn't matter, it is the same for java), and also we store the output in our git repo. Whenever we change something in underlying kotlin classes, we re-generate the yaml and create a PR. because there is no guarantee in generated yaml element ordering, even if we change something very small, we have a huge PR for the yaml part.

**Describe the solution you'd like**
Generate the yaml/json in a way that the ordering is consistent between every generation. This can be achieved by sorting paths, components etc by name while generating the spec.

**Describe alternatives you've considered**

**Additional context**

**Comment by bnasslahsen** [comment]
@kemalizing, 

  This can be an option. But for the solution you are proposing, can you propose a PR?

**Comment by bnasslahsen** [comment]
Closed, as no response here.

**Comment by kemalizing** [comment]
I need to read your source and then find the solution to create a PR for this.. I'll try but I'm not sure when I can create a PR

**Comment by jeff-lauterbach-by** [comment]
I also have a need for this in order to upload the generated spec to an API Gateway.  The generated spec not being consistently ordered which is causing some challenging in our deploiyment pipelines.

I'd be willing to create a PR... but am not familiar with this project source at all yet so any pointers on the code components that might be involved here would help speed this along.

**Comment by jeff-lauterbach-by** [comment]
I've been digging into this and it seems the ordering of Paths is influenced by the order the Spring detects controllers which can vary by machine/env (for me, I noticed it behaved differently whether I lanched springboot from a zsh or bash shell).

I didn't see a very clean way to order the map of HandlerMethods since each method could have multiple patterns specified. 
https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/main/java/org/springdoc/webmvc/api/OpenApiResource.java#L243

I then found some discussion on the swagger-core library that gave an example of adding a mixin to the ObjectMapper to be able to sort properties alphabetically.
https://github.com/swagger-api/swagger-core/pull/3613

As an inital poc, I added a config option to springdoc to support sorting paths and it seems to be working for me to have more stable generated files.

@bnasslahsen and @kemalizing  Does this seem like an okay approach?  I'm happy to create a PR.

**Comment by kemalizing** [comment]
That sounds great Jeff, thanks for your efforts!

**Comment by jeff-lauterbach-by** [comment]
I hit a snag with the mixin approach as Jackson only allows a single mixin per target class and swagger-core is leveraging mixins already.  Still looking into this.

**Comment by PaulFrmBrn** [comment]
Got the same issue. 
I've got an integration/component test that checks that OASv3 schema isn't changed from build to build.
My workaround is to use Jackson to compare trees built from string representations.
```
assertEquals(jacksonObjectMapper.readTree(expected), jacksonObjectMapper.readTree(actual))
```
Not very smart, but works fine with Json.
