### ISSUE TITLE
How to include spring-boot-actuator endpoints to swagger-ui?

### ISSUE THREAD

**Issue by octopus-prime** [springdoc/springdoc-openapi#88]
Would like to see the spring-boot-actuator endpoints in the swagger-ui.
What do i need to do?

**Comment by bnasslahsen** [comment]
Hi, 

 spring-boot-actuator endpoints wer not yet supported as there was no requirements.
 We will start supporting it, from v1.1.38 of springdoc-openapi.

 In order to display them, you will need to add the following property:
 
```properties
springdoc.show.actuator=true
``` 
 Please, test it and give us your feedback.

**Comment by octopus-prime** [comment]
Wow, that was fast!
And it works like a charm!
Thanks a lot!!

What do you think...
Would it be a good idea to tag these endpoints with e.g. "Actuator"?
Currently these endpoints are in "default".
![image](https://user-images.githubusercontent.com/7620013/64918669-a5a0dc00-d7a1-11e9-82bf-f69c1f9b5bcf.png)

**Comment by octopus-prime** [comment]
If you want to try-out actuator-endpoints with parameters
e.g. '/actuator/metrics/{requiredMetricName}'
there is no possibility to enter the parameter.

**Comment by springdoc** [comment]
Hi, 

 For your proposal of adding custom tag name "Actuator", it will be available on  v1.1.39 of springdoc-openapi.
 The the requiredMetricName issue on actuator metrics endpoint, is related to the way spring-boot-actuator is implemented:
 - The actuator implementation in Spring Boot, all actuator endpoints are dynamically mapped to a single handler method: {@link org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping.OperationHandler#handle(javax.servlet.http.HttpServletRequest, java.util.Map)}
- If an Actuator endpoint contains path parameters, these are not available as input fields on the Swagger UI page, because no @PathParam annotated arguments are present on the handler method

Consequently, it will not be possible to execute these actuator endpoints from the Swagger UI page.
You can add a new issue for this behaviour, and we will see if there any workaround about it.

**Comment by octopus-prime** [comment]
Nice! Thanks!!!

I am currently very happy with this solution.
So for the path parameters we can wait until someone needs this requierment.

**Comment by octopus-prime** [comment]
The property was changed to 'springdoc.show-actuator'.
See https://github.com/springdoc/springdoc-openapi/issues/286#issuecomment-568259310

**Comment by bnasslahsen** [comment]
Or you can have a look at the documentation :
- https://springdoc.org/springdoc-properties.html#springdoc-openapi-core-properties

**Comment by ErwanLeroux** [comment]
> Or you can have a look at the documentation :
> 
>     * https://springdoc.org/springdoc-properties.html#springdoc-openapi-core-properties

new link to the doc : https://springdoc.org/properties.html

**Comment by RaulGF92** [comment]
> Hi,
> 
> spring-boot-actuator endpoints wer not yet supported as there was no requirements. We will start supporting it, from v1.1.38 of springdoc-openapi.
> 
> In order to display them, you will need to add the following property:
> 
> ```ini
> springdoc.show.actuator=true
> ```
> 
> Please, test it and give us your feedback.

That is not correct in the actual versions, now looks like this:

`springdoc.show-actuator=true`

**Comment by bnasslahsen** [comment]
@RaulGF92, 

This is correct for `v1.1.38` ...
