### ISSUE TITLE
Special characters not allowed on Request Param of type String

### ISSUE THREAD

**Issue by BESAFX** [springdoc/springdoc-openapi#896]
OS: Ubuntu
Browser: chrome
Version: 22
Method of installation: Java
Swagger-UI version: 3.10.0
Swagger/OpenAPI version: Swagger 2.0, OpenAPI 3.0
I just need to be able to pass special characters like (: < >&&..) on Query param for request,
Like for example following implementation for `@paramter:
@Parameter( in = ParameterIn.QUERY, description = "Enter search query.", name = "search", schema = @Schema( type = "string", pattern = "name:value", defaultValue = "name:value" ) )`

But when i make request from UI, this pattren (name:value) converted into (name%3Avalue) and this will not give me correct response.

So is there any way to force Swagger to accept these special symbols on URLs ?

**Comment by bnasslahsen** [comment]
@BESAFX, 

 You can have a look at the list of special characters (reserved and unreserved) here:
 - https://tools.ietf.org/html/rfc3986#page-12

 That means, that anything that doesn't belong to unreserved characters, will be % encoded, when they do not have special meaning, which is your case.

 There should be no issue while the code is URL encoded, because the spring-boot `@RestController` will decode it correctly.
 If you still believe, you are facing an issue, then please add exactly the following information so this ticket can be reopened:

 - What are the actual and the expected result using OpenAPI Description (yml or json)?
 - Provide a [**Minimal, Reproducible Example - with HelloController**](https://stackoverflow.com/help/minimal-reproducible-example) that explains the issue you are facing.
