### ISSUE TITLE
@Schema(name/description) ignored on DTOs

### ISSUE THREAD

**Issue by hotzen** [springdoc/springdoc-openapi#905]
We have integrated SpringDoc into a SpringBoot Java/Kotlin monolith. When expressing API DTOs in Kotlin as follows

```
@Schema(
        name = "Thing",
        description = """Represents the Thing that..."""
)
data class ThingDto(
        @Schema(description = """Unique, stable/non-changing technical identifier of the Thing""")
        @get:NotBlank
        val uniqueThingReference: String,
)
```
and also enabling `@Schema`-properties in application.properties via `springdoc.api-docs.resolve-schema-properties=true` the resulting openapi.yaml does nevertheless neither honor the name nor the description:

```
...
ThingDto:    << expected to be named `Thing` and also expected to have a `description`
  required:
  - uniqueThingReference
  type: object
  properties:
    uniqueThingReference:
      type: string
...
```

**Comment by bnasslahsen** [comment]
@hotzen, 

 Your issue is not reproducible.
 If you add a [minimal reproducible sample](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc), this ticket can be reopened.

**Comment by jemag** [comment]
@bnasslahsen I have a similar problem, except the schema description is only ignored for some properties, while other works. For example, the following class:
```java
@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
@Schema(name = "Data")
public class Dto {
  @Schema(type = "string", description = "Date in ISO 8601 format UTC")
  private Instant eventDate;
  @Schema(type = "string", description = "another description")
  private String QcFlagCode;
  private Double value;
  private Double uncertainty;
  private String timeSeriesId;
  private Boolean reviewed;

}
```
will only generate the description for the eventDate property:
![image](https://user-images.githubusercontent.com/7985687/97614996-18463880-19f1-11eb-800a-7a641ab3e4e6.png)

Here is the minimal reproducible sample you asked to re-open the issue:
https://github.com/jemag/springdoc-openapi-issue-905

**Comment by bnasslahsen** [comment]
@jemag, 

 First of all, not that on your minimal sample you should remove this useless line from the build.gradle: `implementation org.springdoc:springdoc-openapi-common:1.4.8`
 
Next, your attribute **QcFlagCode**, is not respecting the java naming conventions: It's starting with capital letter.
If you respect the java naming conventions, it will be generated automatically
```java
  @Schema(type = "string", description = "another description")
  private String qcFlagCode;
```

 If you don't want respect the java naming conventions you can add `@JsonProperty` on top of your attribute:
```java
  @Schema(type = "string", description = "another description")
  @JsonProperty("QcFlagCode")
  private String QcFlagCode;
```

 Note there is no issue on the springdoc-openapi code for this. It's directly handled in the [swagger-core](https://github.com/swagger-api/swagger-core) project, which is based on jackson library.

   - Since the setter method is named setQcFlagCode(…), Jackson will assume the variable is named qcFlagCode because of the Java naming conventions (variables should start with lower case letters).

**Comment by jemag** [comment]
my bad, I actually did not even realize that first capital letter, must have been a typo. 

Thank you for the clarification and for the note on springdoc-openapi-common. It does work properly once modified.
