### ISSUE TITLE
Multiple deploy conflict

### ISSUE THREAD

**Issue by luStopai** [springdoc/springdoc-openapi#940]
Hi

**Describe the bug**
I'm having some issues when deploying multiple projects with springdoc as war on the same wildfly instance.
If all projects use the same version of springdoc everything works fine, but if they are different (1.4.6 and 1.4.8 for example) then I can only see swagger-ui on the first project being deployed. On all other projects I get 404

**To Reproduce**
Create a new project with spring-initializr package as war and add springdoc-ui dependency (v1.4.8)
Create a new project with spring-initializr package as war and add springdoc-ui dependency (v1.4.6)
Deploy both to the same instance of wildfly (make sure to use different name and contextroot)

Same thing seems to happen with other combinations of springdoc versions

**Expected behavior**
swagger-ui from both projects should work, but only the first project being deployed works

**Comment by bnasslahsen** [comment]
@luStopai, 

  Make sure you always upgrade to the latest stable version. v1.5.0.
 And it's recommended to use the same latest version across your applications to get the maximum fixes from security, performance and bug fixes.

If using the same version across your application is work. There is no need to look further.

if you believe you are facing an issue, your should provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) - with HelloController that reproduces the problem

 This ticket will be now closed, and can be reopned if the relevant information are provided.

**Comment by luStopai** [comment]
Hi bnasslahsen,

Yes, I know that using the same version works, but I'm pretty sure this didn't happen before. It's not a big deal except that we have to upgrade all applications to a new version at once.

I was also wondering why this might happen. I though that applications couldn't conflict with each other like this. 
Just for curiosity, although you are not going to look further, do you have any clue about what the cause might be?

**Comment by michoudu13820** [comment]
Hello,

Facing the same issue on a Jboss server.
My app is deployed with other war on a Jboss server and one app is using springdoc. If my war is deployed alone there is no problem, but as soon as an other app with springdoc is deployed it doesn't work.

My app was deployed with springfox previously and everyting was working, and since we have migrated to springdoc the web page is not displaying (getting a 404).

Get any solutions @luStopai  ?

**Comment by michoudu13820** [comment]
Found a workaround.

There is a conflict, to access to the swagger index.html, you need to specify the version of swagger included in springdoc-openapi-ui in the url

For exemple here the version is 4.10.3
[INFO] +- org.springdoc:springdoc-openapi-ui:jar:1.6.7:compile
[INFO] |  +- org.webjars:swagger-ui:jar:4.10.3:compile
[INFO] |  +- org.webjars:webjars-locator-core:jar:0.45:compile
[INFO] |  \- io.github.classgraph:classgraph:jar:4.8.143:compile

So to access to your swagger instead of swagger-ui/index.html the url swagger-ui/**4.10.3/i**ndex.html should works.
