### ISSUE TITLE
Can I get the OpenAPI JSON file at non runtime?

### ISSUE THREAD

**Issue by rainysir** [springdoc/springdoc-openapi#963]
**Describe the solution you'd like**
- I want to get the JSON file and generate code  at non runtime, Does this library support it?

**Comment by bnasslahsen** [comment]
You can use the [springdoc-maven-plugin](https://github.com/springdoc/springdoc-openapi-maven-plugin ) during the integration tests.

**Comment by tn185070** [comment]
@bnasslahsen I was looking for this functionality also.

Our WebFlux application has a number of dependencies it requires in order to start, so we could not easily use the spring-boot-maven-plugin to start it up in order to then use the springdoc-maven-plugin. It took me a day to find the right configuration that would let me start the service without its dependencies, on top of another day I spent trying alternatives. 

I am not sure how much effort it would be to offer this functionality, but some users would surely appreciate it. I would update our projects to use it instead of starting the service. The [swagger-maven-plugin](https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-maven-plugin) for jax-rs projects is able to generate an OpenAPI file without starting the service.
